version: "3.7"

services:
    rabbitmq:
        image: rabbitmq:3.11-management
        restart: always
        container_name: rabbitmq
        ports:
          - "5672:5672"  # AMQP port
          - "15672:15672"  # RabbitMQ Management UI port
        
    orderservice:
        image: ghcr.io/faqihyugos/order-service:latest
        restart: always
        container_name: order-service
        ports:
          - "3000:3000"
        depends_on:
          - rabbitmq

    shippingservice:
        image: ghcr.io/faqihyugos/shipping-service:latest
        restart: always
        container_name: shipping-service
        ports:
          - "3001:3001"
        depends_on:
          - rabbitmq

volumes:
  rabbitmq_data: